export const AUTH_START = 'SPK/AUTH_START';
export const AUTH_SUCCESS = 'SPK/AUTH_SUCCESS';
export const AUTH_FAIL = 'SPK/AUTH_FAIL';
export const AUTH_LOGOUT = 'SPK/AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SPK/SET_AUTH_REDIRECT_PATH';

export const SIGNUP_START = 'SPK/SIGNUP_START';
export const SIGNUP_SUCCESS = 'SPK/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SPK/SIGNUP_FAIL';

export const SIGNUP_INIT = 'SPK/SIGNUP_INIT';

export const ORDERS_START = 'SPK/ORDERS_START';
export const ORDERS_SUCCESS = 'SPK/ORDERS_SUCCESS';
export const ORDERS_FAIL = 'SPK/ORDERS_FAIL';

export const TRACKING_SEARCH_START = 'SPK/TRACKING_SEARCH_START';
export const TRACKING_SEARCH_SUCCESS = 'SPK/TRACKING_SEARCH_SUCCESS';
export const TRACKING_SEARCH_FAIL = 'SPK/TRACKING_SEARCH_FAIL';

// 2018-03-14 Review code connect RESTful API
export const JOB_QUERY_START = 'SPK/JOB_QUERY_START';
export const JOB_QUERY_SUCCESS = 'SPK/JOB_QUERY_SUCCESS';
export const JOB_QUERY_FAIL = 'JOB_QUERY_FAIL';

export const JOB_FILTER_START = 'SPK/JOB_FILTER_START';
export const JOB_FILTER_SUCCESS = 'SPK/JOB_FILTER_SUCCESS';
export const JOB_FILTER_FAIL = 'SPK/JOB_FILTER_FAIL';

export const JOB_MODAL_START = 'SPK/JOB_MODAL_START';
export const JOB_MODAL_SUCCESS = 'SPK/JOB_MODAL_SUCCESS';
export const JOB_MODAL_FAIL = 'SPK/JOB_MODAL_FAIL';

export const JOB_TSPOOL_UPDATE_START = 'SPK/JOB_TSPOOL_UPDATE_START';
export const JOB_TSPOOL_UPDATE_SUCCESS = 'SPK/JOB_TSPOOL_UPDATE_SUCCESS';
export const JOB_TSPOOL_UPDATE_FAIL = 'SPK/JOB_TSPOOL_UPDATE_FAIL';

export const SETTINGS_LOAD_START = 'SPK/SETTINGS_LOAD_START';
export const SETTINGS_LOAD_SUCCESS = 'SPK/SETTINGS_LOAD_SUCCESS';
export const SETTINGS_LOAD_FAIL = 'SPK/SETTINGS_LOAD_FAIL';

export const USER_UPDATE_START = 'SPK/USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'SPK/USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'SPK/USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'SPK/USER_UPDATE_RESET';

export const USER_SELECT_START = 'SPK/USER_SELECT_START';
export const USER_SELECT_SUCCESS = 'SPK/USER_SELECT_SUCCESS';
export const USER_SELECT_FAIL = 'SPK/USER_SELECT_FAIL';

export const USER_RESET_PASSWORD_START = 'SPK/USER_RESET_PASSWORD_START';
export const USER_RESET_PASSWORD_SUCCESS = 'SPK/USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'SPK/USER_RESET_PASSWORD_FAIL';

export const ADMIN_UPDATE_USER_START = 'SPK/ADMIN_UPDATE_USER_START';
export const ADMIN_UPDATE_USER_SUCCESS = 'SPK/ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'SPK/ADMIN_UPDATE_USER_FAIL';

export const ADMIN_DELETE_USER_START = 'SPK/ADMIN_DELETE_USER_START';
export const ADMIN_DELETE_USER_SUCCESS = 'SPK/ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAIL = 'SPK/ADMIN_DELETE_USER_FAIL';

export const COMPANY_FETCH_START = 'SPK/COMPANY_FETCH_START';
export const COMPANY_FETCH_SUCCESS = 'SPK/COMPANY_FETCH_SUCCESS';
export const COMPANY_FETCH_FAIL = 'SPK/COMPANY_FETCH_FAIL';

export const COMPANY_INSERT_START = 'SPK/COMPANY_INSERT_START';
export const COMPANY_INSERT_SUCCESS = 'SPK/COMPANY_INSERT_SUCCESS';
export const COMPANY_INSERT_FAIL = 'SPK/COMPANY_INSERT_FAIL';

export const COMPANY_UPDATE_START = 'SPK/COMPANY_UPDATE_START';
export const COMPANY_UPDATE_SUCCESS = 'SPK/COMPANY_UPDATE_SUCCESS';
export const COMPANY_UPDATE_FAIL = 'SPK/COMPANY_UPDATE_FAIL';

export const COMPANY_DELETE_START = 'SPK/COMPANY_DELETE_START';
export const COMPANY_DELETE_SUCCESS = 'SPK/COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAIL = 'SPK/COMPANY_DELETE_FAIL';

export const COMPANY_ADDITEM_START = 'SPK/COMPANY_ADDITEM_START';
export const COMPANY_ADDITEM_SUCCESS = 'SPK/COMPANY_ADDITEM_SUCCESS';


